AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 200

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19

Lint/AmbiguousOperator:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/IndentationWidth:
  Width: 2

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Naming/PredicateName:
  Enabled: true

Naming/MethodName:
  EnforcedStyle: snake_case

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
